Repository geopython/OWSLib, pull requests merged in 2019-10, with the labels that each got.

#615 #614 fix broken TileMapService constructor
  owslib/tms.py
Labels: bug

#611 fix auth in wps
  owslib/wps.py
Labels: bug, wps

#538 added correct checks, defaults and conversion to REST only WMTS
  owslib/wmts.py
  tests/test_wmts.py
Labels: wmts

#621 Update changelog
  CHANGES.rst
  docs/en/index.rst
Labels: documentation

#620 Fix tests suite: wmts, csw geonetwork
  owslib/wmts.py
  tests/doctests/csw_geonetwork.txt
  tests/test_csw_geonetwork.py
  tests/test_wmts.py
Labels: bug
